### ISSUE TITLE
Error when action delete

### ISSUE THREAD

**Issue by KondratevAD** [vb64/django.admin.geomap#34]
Hi, I got an error when trying to delete a list of objects in admin (action). 
What could be the problem?
Python - 3.8
Django - 4.1.1
django-admin-geomap - 1.4 

> Traceback (most recent call last):
  File "/home/krot/Dev/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krot/Dev/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krot/Dev/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/krot/Dev/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/krot/Dev/venv/lib/python3.8/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/krot/Dev/venv/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/krot/Dev/venv/lib/python3.8/site-packages/django_admin_geomap/__init__.py", line 105, in changelist_view
    change_list_queryset = response.context_data['cl'].queryset
Exception Type: KeyError at /admin/carwash/
Exception Value: 'cl'

**Comment by vb64** [comment]
Thanks for report. Will be investigated.

**Comment by KondratevAD** [comment]
> Thanks for report. Will be investigated.

Thanks, maybe I can help?

**Comment by vb64** [comment]
> Thanks, maybe I can help?

Yes. Please update your project up to version 1.5 of the library and check, that error disapper.

Please post your results here.

**Comment by KondratevAD** [comment]
> Please post your results here.

Thanks, everything works.
